name: Weekly Merge
on:
  schedule:
    - cron: 0 0 * * 6
  workflow_dispatch: 
jobs:
  merge_weekly:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: ${{ secrets.AWS_ROLE_SESSION_NAME }}
          aws-region: "ap-southeast-3"
      - name: Merge Now
        run: dotnet run --project BervProject.MergePDFOnline.Console
        env:
          S3__BucketName: ${{ secrets.S3_BUCKET_NAME }}
